services:
  - type: web
    name: mentalmente-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mentalmente-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: citasmentalmente@gmail.com
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: mentalmente-db
    databaseName: mentalmente
    user: mentalmente_user
    plan: free 